name: electrum
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  get_it: ^9.1.1
  injectable: ^2.7.0
  equatable: ^2.0.7
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  slang: ^4.11.0
  slang_flutter: ^4.11.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  intl: ^0.20.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  injectable_generator: ^2.7.0
  build_runner: ^2.7.0
  slang_build_runner: ^4.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

targets:
  $default:
    builders:
      slang_build_runner:
        option:
          base_locale: en
          input_directory: lib/core/localization/i18n
          output_directory: lib/core/localization/generated
          translation_class_visibility: public
          use_flutter_gen: false
